//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakardinKursach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class actions_log
    {
        public int id { get; set; }
        public System.DateTime action_time { get; set; }
        public string action_type { get; set; }
        public int operator_id { get; set; }
        public Nullable<int> call_id { get; set; }
        public Nullable<int> team_id { get; set; }
    
        public virtual emergency_calls emergency_calls { get; set; }
        public virtual operators operators { get; set; }
        public virtual emergency_teams emergency_teams { get; set; }
    }
}
