//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakardinKursach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class call_assignments
    {
        public int call_id { get; set; }
        public int team_id { get; set; }
        public System.DateTime dispatch_time { get; set; }
    
        public virtual emergency_calls emergency_calls { get; set; }
        public virtual emergency_teams emergency_teams { get; set; }
    }
}
