//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakardinKursach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class emergency_calls
    {
        public emergency_calls()
        {
            this.actions_log = new HashSet<actions_log>();
            this.call_assignments = new HashSet<call_assignments>();
        }
    
        public int id { get; set; }
        public System.DateTime call_time { get; set; }
        public string caller_name { get; set; }
        public string caller_location { get; set; }
        public string emergency_type { get; set; }
        public int operator_id { get; set; }
    
        public virtual ICollection<actions_log> actions_log { get; set; }
        public virtual ICollection<call_assignments> call_assignments { get; set; }
        public virtual operators operators { get; set; }
    }
}
