//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakardinKursach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class emergency_teams
    {
        public emergency_teams()
        {
            this.actions_log = new HashSet<actions_log>();
            this.call_assignments = new HashSet<call_assignments>();
        }
    
        public int id { get; set; }
        public string team_name { get; set; }
        public string location { get; set; }
        public bool is_available { get; set; }
    
        public virtual ICollection<actions_log> actions_log { get; set; }
        public virtual ICollection<call_assignments> call_assignments { get; set; }
    }
}
